namespace BMI_Calculator_AZ
{
    partial class Form1
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            panelBaslik = new System.Windows.Forms.Panel();
            lblBaslik = new System.Windows.Forms.Label();
            lblBoy = new System.Windows.Forms.Label();
            txtBoy = new System.Windows.Forms.TextBox();
            lblSm = new System.Windows.Forms.Label();
            lblCeki = new System.Windows.Forms.Label();
            txtCeki = new System.Windows.Forms.TextBox();
            lblKq = new System.Windows.Forms.Label();
            btnHesabla = new System.Windows.Forms.Button();
            btnTemizle = new System.Windows.Forms.Button();
            btnCixis = new System.Windows.Forms.Button();
            panelNetice = new System.Windows.Forms.Panel();
            lblBmi = new System.Windows.Forms.Label();
            lblNetice = new System.Windows.Forms.Label();
            pictureBox1 = new System.Windows.Forms.PictureBox();
            panelMelumat = new System.Windows.Forms.Panel();
            lblMelumat = new System.Windows.Forms.Label();
            lblQeyd = new System.Windows.Forms.Label();
            panelBaslik.SuspendLayout();
            panelNetice.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).BeginInit();
            panelMelumat.SuspendLayout();
            SuspendLayout();
            panelBaslik.BackColor = System.Drawing.Color.FromArgb(44, 62, 80);
            panelBaslik.Controls.Add(lblBaslik);
            panelBaslik.Dock = System.Windows.Forms.DockStyle.Top;
            panelBaslik.Location = new System.Drawing.Point(0, 0);
            panelBaslik.Name = "panelBaslik";
            panelBaslik.Size = new System.Drawing.Size(540, 80);
            panelBaslik.TabIndex = 0;
            lblBaslik.Dock = System.Windows.Forms.DockStyle.Fill;
            lblBaslik.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            lblBaslik.ForeColor = System.Drawing.Color.White;
            lblBaslik.Location = new System.Drawing.Point(0, 0);
            lblBaslik.Name = "lblBaslik";
            lblBaslik.Size = new System.Drawing.Size(540, 80);
            lblBaslik.TabIndex = 0;
            lblBaslik.Text = "BƏDƏN KÜTLƏ İNDEKSİ (BKİ) HESABLAYICI";
            lblBaslik.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            lblBoy.AutoSize = true;
            lblBoy.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            lblBoy.Location = new System.Drawing.Point(40, 100);
            lblBoy.Name = "lblBoy";
            lblBoy.TabIndex = 1;
            lblBoy.Text = "Boyunuzu daxil edin:";
            txtBoy.Font = new System.Drawing.Font("Segoe UI", 14F);
            txtBoy.Location = new System.Drawing.Point(40, 128);
            txtBoy.MaxLength = 10;
            txtBoy.Name = "txtBoy";
            txtBoy.Size = new System.Drawing.Size(390, 32);
            txtBoy.TabIndex = 2;
            lblSm.AutoSize = true;
            lblSm.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            lblSm.Location = new System.Drawing.Point(445, 133);
            lblSm.Name = "lblSm";
            lblSm.TabIndex = 3;
            lblSm.Text = "sm";
            lblCeki.AutoSize = true;
            lblCeki.Font = new System.Drawing.Font("Segoe UI", 10.5F);
            lblCeki.Location = new System.Drawing.Point(40, 175);
            lblCeki.Name = "lblCeki";
            lblCeki.TabIndex = 4;
            lblCeki.Text = "Çəkinizi daxil edin:";
            txtCeki.Font = new System.Drawing.Font("Segoe UI", 14F);
            txtCeki.Location = new System.Drawing.Point(40, 203);
            txtCeki.MaxLength = 10;
            txtCeki.Name = "txtCeki";
            txtCeki.Size = new System.Drawing.Size(390, 32);
            txtCeki.TabIndex = 5;
            lblKq.AutoSize = true;
            lblKq.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            lblKq.Location = new System.Drawing.Point(445, 208);
            lblKq.Name = "lblKq";
            lblKq.TabIndex = 6;
            lblKq.Text = "kq";
            btnHesabla.BackColor = System.Drawing.Color.FromArgb(39, 174, 96);
            btnHesabla.Cursor = System.Windows.Forms.Cursors.Hand;
            btnHesabla.FlatAppearance.BorderSize = 0;
            btnHesabla.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnHesabla.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            btnHesabla.ForeColor = System.Drawing.Color.White;
            btnHesabla.Location = new System.Drawing.Point(40, 262);
            btnHesabla.Name = "btnHesabla";
            btnHesabla.Size = new System.Drawing.Size(140, 44);
            btnHesabla.TabIndex = 7;
            btnHesabla.Text = "HESABLA";
            btnHesabla.UseVisualStyleBackColor = false;
            btnHesabla.Click += btnHesabla_Click;
            btnTemizle.BackColor = System.Drawing.Color.FromArgb(52, 152, 219);
            btnTemizle.Cursor = System.Windows.Forms.Cursors.Hand;
            btnTemizle.FlatAppearance.BorderSize = 0;
            btnTemizle.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnTemizle.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            btnTemizle.ForeColor = System.Drawing.Color.White;
            btnTemizle.Location = new System.Drawing.Point(200, 262);
            btnTemizle.Name = "btnTemizle";
            btnTemizle.Size = new System.Drawing.Size(140, 44);
            btnTemizle.TabIndex = 8;
            btnTemizle.Text = "TƏMİZLƏ";
            btnTemizle.UseVisualStyleBackColor = false;
            btnTemizle.Click += btnTemizle_Click;
            btnCixis.BackColor = System.Drawing.Color.FromArgb(192, 57, 43);
            btnCixis.Cursor = System.Windows.Forms.Cursors.Hand;
            btnCixis.FlatAppearance.BorderSize = 0;
            btnCixis.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            btnCixis.Font = new System.Drawing.Font("Segoe UI", 10.5F, System.Drawing.FontStyle.Bold);
            btnCixis.ForeColor = System.Drawing.Color.White;
            btnCixis.Location = new System.Drawing.Point(360, 262);
            btnCixis.Name = "btnCixis";
            btnCixis.Size = new System.Drawing.Size(140, 44);
            btnCixis.TabIndex = 9;
            btnCixis.Text = "ÇIXIŞ";
            btnCixis.UseVisualStyleBackColor = false;
            btnCixis.Click += btnCixis_Click;
            panelNetice.BackColor = System.Drawing.Color.FromArgb(236, 240, 241);
            panelNetice.Controls.Add(lblBmi);
            panelNetice.Controls.Add(lblNetice);
            panelNetice.Location = new System.Drawing.Point(40, 328);
            panelNetice.Name = "panelNetice";
            panelNetice.Size = new System.Drawing.Size(460, 100);
            panelNetice.TabIndex = 10;
            lblBmi.Font = new System.Drawing.Font("Segoe UI", 16F, System.Drawing.FontStyle.Bold);
            lblBmi.Location = new System.Drawing.Point(0, 10);
            lblBmi.Name = "lblBmi";
            lblBmi.Size = new System.Drawing.Size(460, 40);
            lblBmi.TabIndex = 0;
            lblBmi.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            lblNetice.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            lblNetice.Location = new System.Drawing.Point(0, 50);
            lblNetice.Name = "lblNetice";
            lblNetice.Size = new System.Drawing.Size(460, 42);
            lblNetice.TabIndex = 1;
            lblNetice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            pictureBox1.Location = new System.Drawing.Point(170, 440);
            pictureBox1.Name = "pictureBox1";
            pictureBox1.Size = new System.Drawing.Size(200, 200);
            pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            pictureBox1.TabIndex = 11;
            pictureBox1.TabStop = false;
            panelMelumat.BackColor = System.Drawing.Color.FromArgb(236, 240, 241);
            panelMelumat.Controls.Add(lblMelumat);
            panelMelumat.Location = new System.Drawing.Point(40, 655);
            panelMelumat.Name = "panelMelumat";
            panelMelumat.Size = new System.Drawing.Size(460, 105);
            panelMelumat.TabIndex = 12;
            lblMelumat.Dock = System.Windows.Forms.DockStyle.Fill;
            lblMelumat.Font = new System.Drawing.Font("Segoe UI", 9.5F);
            lblMelumat.Location = new System.Drawing.Point(0, 0);
            lblMelumat.Name = "lblMelumat";
            lblMelumat.Padding = new System.Windows.Forms.Padding(15, 8, 0, 0);
            lblMelumat.Size = new System.Drawing.Size(460, 105);
            lblMelumat.TabIndex = 0;
            lblMelumat.Text = "Çox arıq: < 16\r\nArıq: 16 – 18.4\r\nNormal: 18.5 – 24.9\r\nKök: 25 – 29.9\r\nÇox kök: ≥ 30";
            lblQeyd.Font = new System.Drawing.Font("Segoe UI", 8.5F, System.Drawing.FontStyle.Italic);
            lblQeyd.ForeColor = System.Drawing.Color.DimGray;
            lblQeyd.Location = new System.Drawing.Point(40, 768);
            lblQeyd.Name = "lblQeyd";
            lblQeyd.Size = new System.Drawing.Size(460, 20);
            lblQeyd.TabIndex = 13;
            lblQeyd.Text = "Qeyd: BKİ ümumi məlumat məqsədi daşıyır və tibbi diaqnoz deyil.";
            lblQeyd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            AcceptButton = btnHesabla;
            AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            BackColor = System.Drawing.Color.White;
            ClientSize = new System.Drawing.Size(540, 800);
            Controls.Add(lblQeyd);
            Controls.Add(panelMelumat);
            Controls.Add(pictureBox1);
            Controls.Add(panelNetice);
            Controls.Add(btnCixis);
            Controls.Add(btnTemizle);
            Controls.Add(btnHesabla);
            Controls.Add(lblKq);
            Controls.Add(txtCeki);
            Controls.Add(lblCeki);
            Controls.Add(lblSm);
            Controls.Add(txtBoy);
            Controls.Add(lblBoy);
            Controls.Add(panelBaslik);
            FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "Form1";
            StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            Text = "BMI Calculator AZ";
            panelBaslik.ResumeLayout(false);
            panelNetice.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            panelMelumat.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        private System.Windows.Forms.Panel panelBaslik;
        private System.Windows.Forms.Label lblBaslik;
        private System.Windows.Forms.Label lblBoy;
        private System.Windows.Forms.TextBox txtBoy;
        private System.Windows.Forms.Label lblSm;
        private System.Windows.Forms.Label lblCeki;
        private System.Windows.Forms.TextBox txtCeki;
        private System.Windows.Forms.Label lblKq;
        private System.Windows.Forms.Button btnHesabla;
        private System.Windows.Forms.Button btnTemizle;
        private System.Windows.Forms.Button btnCixis;
        private System.Windows.Forms.Panel panelNetice;
        private System.Windows.Forms.Label lblBmi;
        private System.Windows.Forms.Label lblNetice;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Panel panelMelumat;
        private System.Windows.Forms.Label lblMelumat;
        private System.Windows.Forms.Label lblQeyd;
    }
}
